### ISSUE TITLE
Encoding issue

### ISSUE THREAD

**Issue by math-alpha** [apertium/apertium-byv#3]
hitparade gives the following 
     ^82/82<num>$ ^bò/*bò$
     ^70/70<num>$ ^bô/*bô$

Meaniwhile
~/apertium-byv$ echo "bò" | apertium -d . byv-morph
^bò/bò<prn><pers>$^./.<sent>$

~/apertium-byv$ echo "bô" | apertium -d . byv-morph
^bô/bô<pr>/bô<cnjcoo>$^./.<sent>$

**Comment by math-alpha** [comment]
when I do a direct copy (from hitparade.sh result) and paste in the console, I get

~/apertium-byv$ echo "bò" | apertium -d . byv-morph
^bò/*bò$^./.<sent>$

**Comment by jonorthwash** [comment]
Yes, this is because the lttoolbox analyser (`byv.automorf.bin`) doesn't recognise these characters, but the hfst analyser (`byv.automorf.hfst`) does.

It could be an issue with how they're compiled.  @ftyers, any thoughts?

For now, for analysis, try
```
$ echo "bò" | hfst-proc byv.automorf.hfst
```

**Comment by ftyers** [comment]
The hitparade script and the coverage script are using hfst-proc.

**Comment by jonorthwash** [comment]
@ftyers,  the question is why the lttoolbox binary doesn't seem to include spellrelax variants.  I assume it can just be fixed in the Makefile?

**Comment by math-alpha** [comment]
I found a turnaround. I changed all the occurrences

**Comment by jonorthwash** [comment]
> I found a turnaround. I changed all the occurrences

You're talking about [these change](https://github.com/apertium/apertium-byv/commit/fbbf114dc714fc7473c69dd3a6b1fc5e70d5f71d#diff-38c9f60aecb5b06c86706ab782fb82dfL21), right?  Are you sure these were turned around?

@ana-kuznetsova

**Comment by jonorthwash** [comment]
@math-alpha, could you explain what your changes fixed?
